# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yazin Alirhayim
email: i@yaz.in
description: > # this means to ignore newlines until "baseurl:"
  Technology entrepreneur that loves to do stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yaz.in" # the base hostname & protocol for your site, no trailing /
twitter_username: yazinsai
github_username:  yazinsai
permalink: /:categories/:title/

# Build settings
markdown: kramdown
destination: _site
keep_files:
  - ../assets/

# Defaults
defaults:
  -
    scope:
      path: "machine-learning"
    values:
      timeless: "true"
